### ISSUE TITLE
Seems like only `plans` directory is used from this whole repository

### ISSUE THREAD

**Issue by zmiklank** [sclorg/sclorg-testing-farm#42]
Hi, is there any reason for this repository to contain `roles/`, `group_vars/` and other files expect for readme and `plans/`?

The plan themselves do not seem to include any roles, etc.

CC: @phracek

**Comment by phracek** [comment]
We plan to convert this shell into a playbook, as we do it internally.

I will do it as a rest work.

**Comment by zmiklank** [comment]
Ok, thanks for the information :).
